// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAeiCgCX1-MTaf-HqYLDXt41adLEX0qags',
//     appId: '1:913402940056:web:babf608ed06ef55efbdeed',
//     messagingSenderId: '913402940056',
//     projectId: 'valentine-321',
//     authDomain: 'valentine-321.firebaseapp.com',
//     storageBucket: 'valentine-321.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyB3bjIHU8SVCFkYZEI-6ItsawKOZSw4Ugc',
//     appId: '1:913402940056:android:f8a340006c2bb6b6fbdeed',
//     messagingSenderId: '913402940056',
//     projectId: 'valentine-321',
//     storageBucket: 'valentine-321.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBdPOrv1EFlBVtGmS-ofBWAt30woqEj2Rw',
//     appId: '1:913402940056:ios:6f026086c6351fe9fbdeed',
//     messagingSenderId: '913402940056',
//     projectId: 'valentine-321',
//     storageBucket: 'valentine-321.appspot.com',
//     iosBundleId: 'com.example.valentine',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBdPOrv1EFlBVtGmS-ofBWAt30woqEj2Rw',
//     appId: '1:913402940056:ios:d1555a8fdfcf2366fbdeed',
//     messagingSenderId: '913402940056',
//     projectId: 'valentine-321',
//     storageBucket: 'valentine-321.appspot.com',
//     iosBundleId: 'com.example.valentine.RunnerTests',
//   );
// }
